version: '3.9'

services:
  tea:
    container_name: tea-project
    image: nginx:alpine
    restart: always
    volumes:
      - ./configs:/etc/nginx/conf.d
      - ./:/project
    ports:
      - 3000:80
