version: '3.9'

services:
  tea:
    container_name: restaurnat-meals
    image: nginx:alpine
    restart: always
    volumes:
      - ./configs:/etc/nginx/conf.d
      - .:/project
    ports:
      - 3003:80
